# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gabriel garus
email: gabriel.garus@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Front end focused developer. Experienced in react/redux environments. 
  Good proficiency in CSS/HTML. 
  Eperience in WordPress development
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: Ryshard

# Build settings
markdown: kramdown
permalink: pretty
kramdown:  
  parse_block_html: true
  auto_ids: false

destination: docs

sass:
  sass_dir: css
  style: :compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
